### ISSUE TITLE
Now starting to crash

### ISSUE THREAD

**Issue by BeerCav** [SkyNetCloud/CyberCore_Mod#6]
This hasn't been an issue until just recently. The crash report isn't providing much information as to what exactly is causing it but, I copied a small portion of the report to let you see if you can fix it. At the end it just repeats over and over again until it causes MC to crash.
------------------------------------------------------------------------------------------------------------------------------

[11:14:23] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

-----------------------------------------------------------------------------------------------------------------
**This is the part that starts repeating and eventually crashes MC.**

Caused by: java.lang.StackOverflowError
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}
	at ca.skynetcloud.cybercore.item.enchantment.EnchantmentSoulbound.func_223551_b(EnchantmentSoulbound.java:41) ~[cybercore:?] {re:classloading}

**Comment by SkyNetCloud** [comment]
hmm I'll look into that as soon as I can. Also What version of forge are you using

**Comment by SkyNetCloud** [comment]
This will be fixed in the Next Update

**Comment by BeerCav** [comment]
36.1.0

**Comment by SkyNetCloud** [comment]
Fixed In Ver1.14
